In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Layer

class SimpleDense(Layer):

  def __init__(self, units=32):
      super(SimpleDense, self).__init__()
      self.units = units

  def build(self, input_shape):  # Create the state of the layer (weights)
    w_init = tf.random_normal_initializer()
    self.w = tf.Variable(initial_value=w_init(shape=(input_shape[-1], self.units),
                             dtype='float32'),trainable=True)
    print(self.w)
    b_init = tf.zeros_initializer()
    self.b = tf.Variable(
        initial_value=b_init(shape=(self.units,), dtype='float32'),
        trainable=True)

  def call(self, inputs):  # Defines the computation from inputs to outputs
      return tf.matmul(inputs, self.w) + self.b

# Instantiates the layer.
linear_layer = SimpleDense(4)

# This will also call `build(input_shape)` and create the weights.
y = linear_layer(tf.ones((2, 2)))
assert len(linear_layer.weights) == 2

# These weights are trainable, so they're listed in `trainable_weights`:
assert len(linear_layer.trainable_weights) == 2

<tf.Variable 'simple_dense_8/Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[-0.01322944,  0.07132302,  0.03795496, -0.017215  ],
       [-0.01627793,  0.01821852,  0.00647221,  0.07126114]],
      dtype=float32)>


In [11]:
# Instantiates the layer.
linear_layer = SimpleDense(4)
y=linear_layer(tf.ones((2, 2)))
linear_layer.weights

[<tf.Variable 'simple_dense_7/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[ 0.01977324, -0.00339817, -0.01866575,  0.02040433],
        [ 0.04280616,  0.04252825, -0.01964222,  0.01605006]],
       dtype=float32)>,
 <tf.Variable 'simple_dense_7/Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [29]:
tf.Variable(tf.random_normal_initializer(mean=0., stddev=2.)(shape=[3], dtype=tf.float32))

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([ 4.6787677 , -2.6661477 ,  0.66852665], dtype=float32)>

In [73]:
class SimpleDense2(Layer):

  def __init__(self, units=32):
      super(SimpleDense2, self).__init__()
      self.units = units

  def build(self, input_shape):
      print(input_shape[-1],self.units)
      self.w = self.add_weight(shape=(input_shape[-1], self.units),
                               initializer='random_normal',
                               trainable=True)
      self.b = self.add_weight(shape=(self.units,),
                               initializer='zero',
                               trainable=True)

  def call(self, inputs):
      return tf.matmul(inputs, self.w) + self.b

In [39]:
# Instantiates the layer.
linear_layer = SimpleDense(4)
y=linear_layer(tf.ones((2, 2)))
linear_layer.weights

2 4


[<tf.Variable 'simple_dense_13/Variable:0' shape=(2, 4) dtype=float32, numpy=
 array([[-0.0273477 ,  0.01179164,  0.00472138, -0.06082397],
        [-0.02626987,  0.04275491, -0.07079419,  0.05486948]],
       dtype=float32)>,
 <tf.Variable 'simple_dense_13/Variable:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>]

In [40]:
mt=tf.constant([[2,3,3],[4,5,6]])

In [42]:
tf.reduce_sum(mt)

<tf.Tensor: shape=(), dtype=int32, numpy=23>

In [49]:
 tf.Variable(initial_value=tf.zeros((2,)),trainable=False).assign_add(tf.reduce_sum(tf.ones((2, 2)), axis=0))

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([2., 2.], dtype=float32)>

In [50]:
class ComputeSum(Layer):

  def __init__(self, input_dim):
      super(ComputeSum, self).__init__()
      # Create a non-trainable weight.
      self.total = tf.Variable(initial_value=tf.zeros((input_dim,)),
                               trainable=False)

  def call(self, inputs):
      self.total.assign_add(tf.reduce_sum(inputs, axis=0))
      return self.total

my_sum = ComputeSum(2)
x = tf.ones((2, 2))

y = my_sum(x)
print(y.numpy())  # [2. 2.]

y = my_sum(x)
print(y.numpy())  # [4. 4.]

assert my_sum.weights == [my_sum.total]
assert my_sum.non_trainable_weights == [my_sum.total]
assert my_sum.trainable_weights == []

[2. 2.]
[4. 4.]


In [52]:
tf.convert_to_tensor([[1., 2., 3.]])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>

In [60]:
layer_a = tf.keras.layers.Dense(1,  kernel_initializer=tf.constant_initializer(1.))
a_out = layer_a(tf.convert_to_tensor([[1., 2., 3.]]))
layer_a

In [58]:
a_out

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[6.]], dtype=float32)>

In [61]:
layer_b = tf.keras.layers.Dense(1, kernel_initializer=tf.constant_initializer(2.))

b_out = layer_b(tf.convert_to_tensor([[10., 20., 30.]]))

layer_b.get_weights()

[array([[2.],
        [2.],
        [2.]], dtype=float32),
 array([0.], dtype=float32)]

In [63]:
layer_b.set_weights(layer_a.get_weights())
layer_b.get_weights()

[array([[1.],
        [1.],
        [1.]], dtype=float32),
 array([0.], dtype=float32)]

In [65]:
# define the dataset
import numpy as np
xs = np.array([-1.0,  0.0, 1.0, 2.0, 3.0, 4.0], dtype=float)
ys = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=float)

In [74]:
model=tf.keras.models.Sequential([SimpleDense2(units=1)])

model.compile(optimizer="sgd",loss="mse")
model.fit(xs,ys, epochs=500, verbose=0)

1 1


In [75]:
model.predict([-1])

array([[-2.9889789]], dtype=float32)