In [1]:
import tensorflow as tf 
import numpy as np

In [3]:
x=np.arange(0,25)

In [5]:
x=tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

In [6]:
x=tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int32, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

In [7]:
x=tf.reshape(x,(5,5))
x

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

In [9]:
tmp=tf.constant([1,2,3,4])
tf.reshape(tmp, shape=[2,2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [13]:
x=tf.cast(x, dtype=tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

In [15]:
y=tf.constant(2,dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [16]:
result=tf.multiply(x,y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

In [17]:
# Now let's define an array that matches the number of row elements in the `x` array.
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [18]:
# Add tensor `x` and `y`. `y` is added element wise to each row of `x`.
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

In [19]:
tf.constant([1,2,3,4], shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [21]:
try:
    # This will produce a ValueError
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # See what the ValueError says
    print(v)

The initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).


In [2]:
### Eagerness Tensors
def fit_data(real_x, real_y):
    with tf.GradientTape(persistent=True) as tape:
        ## make prediction
        pred_y=w*real_x+b
        # calculate loss 
        reg_loss-simple_loss(real_y, pred_y)
        
    ## calculate gradients
    w_gradient=tape.gradient(reg_loss, w)
    b_gradient=tape.gradient(reg_loss, b)
    
    ## update variable 
    w.assign_sub(w_gradientgradient*LEARNING_RATE)
    v=b.assign_sub(b_gradientgradient*LEARNING_RATE)

In [4]:
w=tf.Variable([[1.0]])

with tf.GradientTape() as tape:
    loss=w*w*w
    
tape.gradient(loss, w)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[3.]], dtype=float32)>

In [6]:
x=tf.ones((2,2))

with tf.GradientTape( ) as t:
    t.watch(x)
    
    y=tf.reduce_sum(x)
    
    z=tf.square(y)
    
dz_dx=t.gradient(z,x)
dz_dx

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [8]:
x=tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
    t.watch(x)
    y=x*x
    z=y*y
dz_dz=t.gradient(z,x)
dz_dz

<tf.Tensor: shape=(), dtype=float32, numpy=108.0>

In [9]:
x=tf.Variable(1.0)

with tf.GradientTape() as tape_2: 
    with tf.GradientTape() as tape_1:
        y=x*x*x
    dy_dx=tape_1.gradient(y,x)
d2y_dx2=tape_2.gradient(dy_dx,x)

assert dy_dx.numpy()==3.0
assert d2y_dx2.numpy()==6.0

In [10]:
tf.Variable([-1, -1, -1, -1, -1, -1], tf.int32, shape=[2,3])

ValueError: The initial value's shape ((6,)) is not compatible with the explicitly supplied `shape` argument ([2, 3]).

In [11]:


tf.constant([-1, -1, -1, -1, -1, -1], shape=[2, 3])


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]])>

In [12]:
tf.Variable([[-1, -1, -1], [-1, -1, -1]], dtype=tf.int32)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]])>

In [13]:
tf.Variable([[-1, -1, -1], [-1, -1, -1]], shape=[2, 3])

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]])>

In [16]:
a=tf.constant([[5,7], [2,1]])
b=tf.add(a,2)
c=b**2
print(c)
d=tf.reduce_sum(c)
print(d)

tf.Tensor(
[[49 81]
 [16  9]], shape=(2, 2), dtype=int32)
tf.Tensor(155, shape=(), dtype=int32)
